#!/bin/bash
if [ $(docker images -q --filter reference=ppaludo/oci-cli | wc -l) -eq 0 ]; then
	echo "Downloading container image..."
	docker pull ppaludo/oci-cli:latest
else
	docker run --rm -ti -p 8181:8181 -v ${HOME}/.oci:/root/.oci ppaludo/oci-cli $*
fi
